favicon: null
name: storytellersoflife
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7191489
  brandStrength: 0.25
  lightness: 0.3765957
  brandColors:
    - '#161417'
    - '#fefefe'
    - '#aa6d62'
    - '#5c575e'
    - '#afa293'
  rhythmicContrast: 0.7638298
typography_spectrum: 0.40223
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2617021
analytics:
  twitter: null
  google: null
  facebook: null
