name: storytellersoflife
favicon: null
layout_spectrum: 0.7546794016379863
typography_spectrum: 0.00026453612372279167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6019247542135417
  lightness: 0.8463839665055275
  saturation: 0.5222617615945637
  rhythmicContrast: 0.9246885583270341
purpose: []
