favicon: null
name: storytellersoflife
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5106383
  brandStrength: 0.5170213
  lightness: 1
  brandColors:
    - '#F1F1F1'
    - '#000000'
    - '#A5A5A5'
    - '#38393D'
    - '#AE7D01'
  rhythmicContrast: 0
typography_spectrum: 0.2276596
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4978724
analytics:
  twitter: null
  google: null
  facebook: null
