favicon: null
name: storytellersoflife
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5404255
  brandStrength: 0.25
  rhythmicContrast: 0.6234043
  brandColors:
    - '#161417'
    - '#fefefe'
    - '#aa6d62'
    - '#5c575e'
    - '#afa293'
  lightness: 0.7808511
typography_spectrum: 0.40223
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2617021
analytics:
  twitter: null
  google: null
  facebook: null
