favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0.5234042
  lightness: 0.493617
  brandColors:
    - '#010104'
    - '#395B78'
    - '#01304C'
    - '#423843'
    - '#AC8988'
  rhythmicContrast: 1
typography_spectrum: 0.3085106
layout_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
name: storytellersoflife
